# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: skein 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "skein"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Scott Tadman"]
  s.date = "2016-11-16"
  s.description = "Wrapper for RabbitMQ that makes blocking RPC calls and handles pub-sub broadcasts."
  s.email = "tadman@postageapp.com"
  s.executables = ["skein"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/skein",
    "config/.gitignore",
    "config/skein.yml.example",
    "lib/skein.rb",
    "lib/skein/broker.rb",
    "lib/skein/client.rb",
    "lib/skein/config.rb",
    "lib/skein/connected.rb",
    "lib/skein/context.rb",
    "lib/skein/publisher.rb",
    "lib/skein/rabbitmq.rb",
    "lib/skein/receiver.rb",
    "lib/skein/reporter.rb",
    "lib/skein/rpc.rb",
    "lib/skein/rpc/base.rb",
    "lib/skein/rpc/error.rb",
    "lib/skein/rpc/notification.rb",
    "lib/skein/rpc/request.rb",
    "lib/skein/rpc/response.rb",
    "lib/skein/subscriber.rb",
    "lib/skein/support.rb",
    "test/data/sample_config.yml",
    "test/helper.rb",
    "test/unit/test_skein_broker.rb",
    "test/unit/test_skein_client.rb",
    "test/unit/test_skein_config.rb",
    "test/unit/test_skein_context.rb",
    "test/unit/test_skein_publisher.rb",
    "test/unit/test_skein_rabbitmq.rb",
    "test/unit/test_skein_receiver.rb",
    "test/unit/test_skein_reporter.rb",
    "test/unit/test_skein_rpc_error.rb",
    "test/unit/test_skein_rpc_request.rb",
    "test/unit/test_skein_subscriber.rb",
    "test/unit/test_skein_support.rb",
    "tmp/.gitignore"
  ]
  s.homepage = "http://github.com/postageapp/skein"
  s.licenses = ["closed"]
  s.rubygems_version = "2.5.1"
  s.summary = "RabbitMQ RPC/PubSub Library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<birling>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<birling>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<birling>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

